// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/5262c27b6ec4786e543c32ac83ef0b5b687987b5/redux-promise/redux-promise.d.ts
declare namespace Redux {
	type PromiseAction<S> = (dispatch: Redux.Dispatch<S>, getState?: () => S) => any;

	interface Dispatch<S> {
		<R>(asyncAction: PromiseAction<S>): R;
	}
}

declare namespace ReduxPromise {
	export interface Promise extends Redux.Middleware {}
}

declare module "redux-promise" {
	var promise: ReduxPromise.Promise;
	export = promise;
}
